#!/bin/bash
set -e

case "$1" in
    remove|purge)
        # Stop service
        if [ -d /run/systemd/system ]; then
            systemctl stop go-socks5 || true
            systemctl disable go-socks5 || true
        fi
        ;;
    
    upgrade|deconfigure)
        ;;
    
    *)
        ;;
esac

exit 0